## SVM

In [10]:
import numpy as np
import os
from multilabel import *
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
%matplotlib inline

## Prepare Data

In [11]:
random_seed = 20230531

files = [
    'rest.csv',
    '12.csv',
    '13.csv',
    '14.csv',
    '15.csv',
    '23.csv',
    '24.csv',
    '25.csv',
    '34.csv',
    '35.csv',
    '45.csv',
    '123.csv',
    '124.csv',
    '125.csv',
    '234.csv',
    '235.csv',
    '1234.csv',
    '1235.csv',
    '1245.csv',
    '1345.csv',
    '2345.csv',
    '12345.csv'
]

# Load data
path = os.path.abspath(os.getcwd()) # Get current path
X_train, labels_train, list_ch_train, X_test, labels_test, list_ch_test = read_training_data(
    data_path='%s%sdatasets/dataset4%s' % (path, os.sep, os.sep),
    files=files,
    shuffle=True,
    sub_split=True,
)

assert list_ch_train == list_ch_test, 'Mismatch in channels!'

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 ...
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
(4268, 5, 3)
(4268, 150, 3)
[[0 0 0 0 0]
 [1 1 1 1 0]
 [0 0 0 0 0]
 ...
 [1 0 1 1 1]
 [1 1 0 1 1]
 [1 1 0 1 1]]
[[[-109.98005486 -101.17316265  -71.76079429]
  [-115.24092547 -108.21181664  -71.81503905]
  [-123.56113475 -118.95815538  -72.04056692]
  ...
  [-118.66799409 -109.7837118   -72.15501898]
  [-112.41451461 -102.171549    -71.60039946]
  [-109.68994194  -99.11596249  -71.14261653]]

 [[ -14.78151962   45.11658884   -6.54562104]
  [  -4.55737946   35.17379428    2.95006828]
  [  -2.02522035   15.97961711   16.09665353]
  ...
  [ -14.42628557   12.11107173    8.20721529]
  [  -2.54519799    7.31979938   11.5548347 ]
  [  -1.5367895     0.56560396   13.12646771]]

 [[-116.9015196  -111.20783191  -72.60155174]
  [-110.52259513 -103.00303702  -72.74789252]
  [-107.76279265  -99.35772236  -73.0232415 ]
  ...
  [-125.08277286 -121.44868551  -71.50044511]
  [-135.19038968 -134.76898293  -71.79673731]


In [12]:
X_train, X_test = standardize(X_train, X_test)

In [13]:
print(X_train[2200], X_train.shape)
X_train = X_train.reshape(X_train.shape[0], -1)
X_test = X_test.reshape(X_test.shape[0], -1) 

[[ 2.51913517e-01  1.27449887e+00 -2.55061911e-01]
 [-5.58679138e-01  1.93310832e+00 -3.93745230e-02]
 [ 4.43173911e-01  2.53921059e+00  1.52670821e-01]
 [ 1.36419133e+00  3.01054496e+00  2.99952231e-01]
 [ 2.10591778e+00  3.25262867e+00  3.93321572e-01]
 [ 2.60918655e+00  3.23170021e+00  4.34684770e-01]
 [ 2.82595009e+00  2.97878246e+00  4.27113098e-01]
 [ 2.73635143e+00  2.55918808e+00  3.69666371e-01]
 [ 2.32213359e+00  1.98016270e+00  2.68688262e-01]
 [ 1.61229670e+00  1.24424234e+00  1.45645202e-01]
 [ 6.96339343e-01  3.54616406e-01  2.14355797e-02]
 [-3.22388271e-01 -5.89957145e-01 -8.95295636e-02]
 [ 8.08705083e-02  5.16697506e-01 -1.93824598e-01]
 [ 1.05099812e+00  1.60521028e+00 -3.09613386e-01]
 [ 1.90120704e+00  2.56221485e+00 -4.53386467e-01]
 [ 2.59524414e+00  3.31788398e+00 -5.67160567e-01]
 [ 3.08523751e+00  3.80420907e+00 -4.05665558e-01]
 [ 3.31366359e+00  3.99813599e+00 -2.28961595e-01]
 [ 3.25311140e+00  3.89788190e+00 -4.68510917e-02]
 [ 2.92715345e+00  3.52957456e+

## Fit and Evaluate Model

In [14]:
from sklearn.svm import SVC
from sklearn.multioutput import MultiOutputClassifier
from sklearn.metrics import accuracy_score

# 建立SVM分類器
svm_classifier = SVC()

# 將SVM分類器轉換為多標籤分類器
multi_label_classifier = MultiOutputClassifier(svm_classifier)

# 訓練多標籤分類器
multi_label_classifier.fit(X_train, labels_train)

# 預測新的樣本
y_pred = multi_label_classifier.predict(X_test)
accuracy = accuracy_score(labels_test, y_pred)
print("Accuracy:", accuracy)

In [ ]:
l = len(labels_test)
score = 0
for i in range(l):
    for j in range(5):
        if labels_test[i][j] == y_pred[i][j]:
            score += 1
print('score:', score / (l * 5))

score: 0.8184247538677918
