## SVM

In [1]:
import numpy as np
import os
from multilabel import *
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
%matplotlib inline

## Prepare Data

In [2]:
random_seed = 20230531

files = [
    'rest.csv',
    '12.csv',
    '13.csv',
    '14.csv',
    '15.csv',
    '23.csv',
    '24.csv',
    '25.csv',
    '34.csv',
    '35.csv',
    '45.csv',
    '123.csv',
    '124.csv',
    '125.csv',
    '234.csv',
    '235.csv',
    '1234.csv',
    '1235.csv',
    '1245.csv',
    '1345.csv',
    '2345.csv',
    '12345.csv'
]

# Load data
path = os.path.abspath(os.getcwd()) # Get current path
X_train, labels_train, list_ch_train, X_test, labels_test, list_ch_test = read_training_data(
    data_path='%s%sdatasets/dataset4%s' % (path, os.sep, os.sep),
    files=files,
    shuffle=True,
    sub_split=True,
)

assert list_ch_train == list_ch_test, 'Mismatch in channels!'

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 ...
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
(4268, 5, 3)
(4268, 150, 3)
[[0 1 0 1 0]
 [0 1 0 1 0]
 [1 0 0 0 1]
 ...
 [1 1 1 1 1]
 [1 0 1 0 0]
 [0 1 1 1 1]]
[[[-5.80048851e+01  1.31811041e+02 -1.25068603e+01]
  [-4.16168274e+01  1.32530760e+02  3.76143103e+00]
  [-2.38920868e+01  1.13325285e+02  1.64767691e+01]
  ...
  [ 1.37842933e+02  8.95835529e+01 -1.98104393e+01]
  [ 9.94425187e+01  8.17051562e+01 -1.13677831e+01]
  [ 4.34339034e+01  6.38192542e+01 -6.25661768e+00]]

 [[-5.53145757e+01 -3.96772466e+01 -1.68903597e+01]
  [-1.71092112e+01 -3.68255816e+01 -1.57595417e+01]
  [ 8.50247995e+00 -3.08882066e+01 -1.58651696e+01]
  ...
  [ 2.40209019e+01  1.55805986e+01 -1.88374224e+01]
  [ 3.32310588e+01  3.18605924e+01 -1.01366612e+01]
  [ 3.89874518e+01  4.49735808e+01 -4.13171058e+00]]

 [[-4.59167474e+01 -6.78731217e+01 -4.12052359e+01]
  [-3.86851727e+01 -7.01836624e+01 -3.63465094e+01]
  [-3.82114576e+01 -7.31722315e+01 -3.07708209e+01]
  ...
  

In [3]:
X_train, X_test = standardize(X_train, X_test)

In [4]:
print(X_train[2200], X_train.shape)
X_train = X_train.reshape(X_train.shape[0], -1)
X_test = X_test.reshape(X_test.shape[0], -1) 

[[ 2.45203743e+00  2.61008394e+00  8.47814263e-01]
 [ 3.21649103e+00  3.17892837e+00  9.52571815e-01]
 [ 3.57104477e+00  3.47945127e+00  8.81350398e-01]
 [ 3.48623888e+00  3.47044591e+00  6.42915708e-01]
 [ 2.99369796e+00  3.15336500e+00  2.81048654e-01]
 [ 2.18040519e+00  2.58776649e+00 -1.41557106e-01]
 [ 1.14198948e+00  1.90207889e+00  2.85279047e-01]
 [ 5.27808565e-03  1.19782249e+00  6.61190041e-01]
 [ 8.30584609e-01  5.28824376e-01  9.25690196e-01]
 [ 1.71812330e+00 -7.63711096e-02  1.03277723e+00]
 [ 2.30652388e+00  2.87490411e-01  9.67849338e-01]
 [ 2.53926708e+00  7.26115842e-01  7.62952843e-01]
 [ 2.41410634e+00  1.06084675e+00  4.76093695e-01]
 [ 1.98876323e+00  1.26992131e+00  1.73000621e-01]
 [ 1.33540942e+00  1.33566875e+00 -1.04793315e-01]
 [ 5.43886494e-01  1.26379013e+00  7.51736937e-02]
 [ 3.78746104e-02  1.07409274e+00  2.39652746e-01]
 [ 8.30975136e-01  8.14379718e-01  3.53602805e-01]
 [ 1.48507234e+00  5.36478053e-01  4.09169109e-01]
 [ 1.92809937e+00  2.90796658e-

## Fit and Evaluate Model

In [5]:
from sklearn.svm import SVC
from sklearn.multioutput import MultiOutputClassifier
from sklearn.metrics import accuracy_score

svm_classifier = SVC()

multi_label_classifier = MultiOutputClassifier(svm_classifier)
multi_label_classifier.fit(X_train, labels_train)

y_pred = multi_label_classifier.predict(X_test)
accuracy = accuracy_score(labels_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.30168776371308015


In [6]:
l = len(labels_test)
score = 0
for i in range(l):
    for j in range(5):
        if labels_test[i][j] == y_pred[i][j]:
            score += 1
print('score:', score / (l * 5))

score: 0.8137834036568213
