# Random Forest

In [1]:
import numpy as np
import os
from multilabel import *
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
%matplotlib inline

/home/steven/.local/lib/python3.8/site-packages/pandas/core/computation/expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED


## Prepare Data

In [2]:
random_seed = 20230531

files = [
    'rest.csv',
    '12.csv',
    '13.csv',
    '14.csv',
    '15.csv',
    '23.csv',
    '24.csv',
    '25.csv',
    '34.csv',
    '35.csv',
    '45.csv',
    '123.csv',
    '124.csv',
    '125.csv',
    '234.csv',
    '235.csv',
    '1234.csv',
    '1235.csv',
    '1245.csv',
    '1345.csv',
    '2345.csv',
    '12345.csv'
]

# Load data
path = os.path.abspath(os.getcwd()) # Get current path
X_train, labels_train, list_ch_train, X_test, labels_test, list_ch_test = read_training_data(
    data_path='%s%sdatasets/dataset4%s' % (path, os.sep, os.sep),
    files=files,
    shuffle=True,
    sub_split=True,
)

assert list_ch_train == list_ch_test, 'Mismatch in channels!'

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 ...
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
(4268, 5, 3)
(4268, 150, 3)
[[0 0 0 0 0]
 [1 0 1 1 1]
 [0 0 0 0 0]
 ...
 [0 1 0 1 0]
 [0 0 1 1 0]
 [0 0 0 0 0]]
[[[-129.55076342 -125.02521482  -72.66317768]
  [-134.81381476 -131.42820525  -72.59426103]
  [-124.66791302 -118.47421486  -72.50820587]
  ...
  [-109.26502411  -98.44640882  -72.45787792]
  [-112.46602081 -102.63262243  -72.64064615]
  [-119.17484766 -111.28430731  -72.76729817]]

 [[  64.537179     -0.95612872   28.23120756]
  [  26.32605381    7.28268354   16.01779883]
  [  -4.5673848    10.66135452   -0.59689251]
  ...
  [  43.32447964   72.53300831   13.42874012]
  [  39.04084664   56.15888499    8.4632753 ]
  [  23.36565362   32.26093965    3.75684226]]

 [[-132.03247257 -128.91075053  -71.53770895]
  [-132.05765315 -127.48873424  -71.52084374]
  [-122.11368898 -115.09176063  -71.69485562]
  ...
  [-110.01369165  -99.61071951  -71.92253158]
  [-114.24334057 -105.29564921  -71.73531844]


In [3]:
X_train, X_test = standardize(X_train, X_test)

#### Reshape

In [4]:
X_train = X_train.reshape(X_train.shape[0], -1)
X_test = X_test.reshape(X_test.shape[0], -1) 

## Fit and Evaluate Model

In [5]:
# Data Processing
import pandas as pd
import numpy as np

# Modelling
from sklearn.ensemble import RandomForestClassifier
from sklearn.multioutput import MultiOutputClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, ConfusionMatrixDisplay
from sklearn.model_selection import RandomizedSearchCV, train_test_split
from scipy.stats import randint

# Tree Visualisation
from sklearn.tree import export_graphviz
from IPython.display import Image

In [6]:
# rf = RandomForestClassifier(random_state=random_seed)
# rf.fit(X_train, labels_train)
clf = MultiOutputClassifier(DecisionTreeClassifier())
clf.fit(X_train, labels_train)


MultiOutputClassifier(estimator=DecisionTreeClassifier(ccp_alpha=0.0,
                                                       class_weight=None,
                                                       criterion='gini',
                                                       max_depth=None,
                                                       max_features=None,
                                                       max_leaf_nodes=None,
                                                       min_impurity_decrease=0.0,
                                                       min_impurity_split=None,
                                                       min_samples_leaf=1,
                                                       min_samples_split=2,
                                                       min_weight_fraction_leaf=0.0,
                                                       presort='deprecated',
                                                       random_state=None,
             

In [7]:
y_pred = clf.predict(X_test)
accuracy = accuracy_score(labels_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.3888888888888889


## Test


In [8]:
from test import *
# files = [
#     'rest.csv',
#     '1st.csv',
#     '2nd.csv',
#     '3rd.csv',
#     '4th.csv',
#     '5th.csv',
# ]
files = [
    'rest.csv',
    '12.csv',
    '13.csv',
    '14.csv',
    '15.csv',
    '23.csv',
    '24.csv',
    '25.csv',
    '34.csv',
    '35.csv',
    '45.csv',
    '123.csv',
    '234.csv',
    '2345.csv',
    '12345.csv',
]
# files = [
#     'rest.csv',
#     '123_手心朝上.csv',
# ]
# read 
# test_classes = len(files)
# path = os.path.abspath(os.getcwd()) # Get current path
# X_test, labels_test, list_ch_test = read_testing_data(
#     data_path='%s%stest_datasets/testdata3%s' % (path, os.sep, os.sep),
#     files=files,
#     n_classes=test_classes
# )

# # standardlize and reshape
# X_test = (X_test - np.mean(X_test, axis=0)[None, :, :]) / np.std(X_test, axis=0)[None, :, :]
# X_test = X_test.reshape(X_test.shape[0], -1) 

In [9]:
y_pred = clf.predict(X_test)
accuracy = accuracy_score(labels_test, y_pred)
print('actual:', labels_test)
print('pred:', y_pred)
print("Accuracy:", accuracy)

# my score function
l = len(labels_test)
score = 0
for i in range(l):
    for j in range(5):
        if labels_test[i][j] == y_pred[i][j]:
            score += 1
print('score:', score / (l * 5))

actual: [[0 0 0 0 0]
 [1 0 1 1 1]
 [0 0 0 0 0]
 ...
 [1 1 1 0 1]
 [1 0 1 1 1]
 [1 1 0 1 1]]
pred: [[0 0 0 0 0]
 [1 0 1 1 1]
 [0 0 0 0 0]
 ...
 [0 0 1 1 1]
 [1 1 0 1 1]
 [1 1 1 1 1]]
Accuracy: 0.3888888888888889
score: 0.7976090014064697
